<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\SourceMessageSearch $searchModel
 */

$this->title = 'Source Message';
$this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('_search') ?>


<?php if ($model != []) : ?>
    <?= $this->render('_index', [
        'model' => $model,
        'data' => $data,
    ])
    ?>
<?php endif ?>