<?php
/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\ModalButton;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
* @var app\models\search\SupplierBarangSearch $searchModel
*/

$this->title = 'Supplier Barang';
$this->params['breadcrumbs'][] = $this->title;
?>

<p>

            <?= ModalButton::a('<i class="fa fa-plus"></i>' . 'Tambah Baru', ['create'], ['class' => 'btn btn-success', 'title' => 'Tambah Baru']) ?>
    </p>


    <?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-body">
                <div class="table-responsive">
                    <?= GridView::widget([
                        'layout' => '{summary}{items}{pager}',
                        'dataProvider' => $dataProvider,
                        'pager'        => [
                            'class'          => app\components\annex\LinkPager::className(),
                            'firstPageLabel' => 'First',
                            'lastPageLabel'  => 'Last'                        ],
                        'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table table-striped table-borderless table-hover'],
                        'headerRowOptions' => ['class'=>'x'],
                        'columns' => [

                            \app\components\ActionAjaxButton::getButtons(['template' => '{view} {update}']),

				[
            'attribute' => 'supplier_id',
            'format' => 'text',
        ],
				[
            'attribute' => 'submaterial_id',
            'format' => 'text',
        ],
				[
            'attribute' => 'nama_barang',
            'format' => 'text',
        ],
				[
            'attribute' => 'slug',
            'format' => 'text',
        ],
				[
            'attribute' => 'satuan_id',
            'format' => 'text',
        ],
				[
            'attribute' => 'stok',
            'format' => 'text',
        ],
				[
            'attribute' => 'harga_ritel',
            'format' => 'rp',
        ],
			/*[
            'attribute' => 'harga_proyek',
            'format' => 'rp',
        ],*/
			/*[
            'attribute' => 'minimal_beli_satuan',
            'format' => 'text',
        ],*/
			/*[
            'attribute' => 'minimal_beli_volume',
            'format' => 'text',
        ],*/
			/*[
            'attribute' => 'deskripsi',
            'format' => 'ntext',
        ],*/
			/*[
            'attribute' => 'gambar',
            'format' => 'ntext',
        ],*/
			/*[
            'attribute' => 'material_id',
            'format' => 'text',
        ],*/
			/*[
            'attribute' => 'panjang',
            'format' => 'text',
        ],*/
			/*[
            'attribute' => 'lebar',
            'format' => 'text',
        ],*/
			/*[
            'attribute' => 'tebal',
            'format' => 'text',
        ],*/
			/*[
            'attribute' => 'created_by',
            'format' => 'text',
        ],*/
			/*[
            'attribute' => 'updated_by',
            'format' => 'iddate',
        ],*/
			/*[
            'attribute' => 'deleted_by',
            'format' => 'text',
        ],*/
			/*[
            'attribute' => 'status',
            'format' => 'text',
        ],*/
			/*[
            'attribute' => 'flag',
            'format' => 'boolean',
        ],*/
			/*[
            'attribute' => 'params',
            'format' => 'ntext',
        ],*/
			/*[
            'attribute' => 'created_at',
            'format' => 'iddate',
        ],*/
			/*[
            'attribute' => 'updated_at',
            'format' => 'iddate',
        ],*/
			/*[
            'attribute' => 'id',
            'format' => 'text',
        ],*/
\app\components\ActionAjaxButton::getButtons(['template' => '{delete}']),
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
        <?php \yii\widgets\Pjax::end() ?>
        