<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use dosamigos\selectize\SelectizeDropDownList;
use dosamigos\selectize\SelectizeTextInput;

/**
 * @var yii\web\View $this
 * @var app\modules\blog\models\Post $model
 * @var app\components\annex\ActiveForm $form
 */

?>

<div class="clearfix"></div>
<div class="d-flex  flex-wrap">
    <!-- preview image -->
    <?php if (!$model->isNewRecord) : ?>
        <div class="col-md-12 text-center">
            <?= Yii::$app->formatter->asMyImage($model->image) ?>
        </div>
    <?php endif ?>
    <?= $form->field($model, 'image', \app\components\Constant::COLUMN(1))->widget(\kartik\file\FileInput::className(), [
        'options' => ['accept' => 'image/*'],
        'pluginOptions' => [
            'allowedFileExtensions' => ['jpg', 'png', 'jpeg', 'gif', 'bmp'],
        ],
    ]) ?>
    <?= $form->field($model, 'tag', \app\components\Constant::COLUMN(1))->widget(SelectizeTextInput::class, [
        'options' => ['class' => 'form-control'],
        'clientOptions' => [
            'plugins' => ['remove_button'],
            'valueField' => 'name',
            'labelField' => 'name',
            'searchField' => ['name'],
            'create' => true,
            'delimiter' => ',',
        ],
    ]) ?>
    <?= $form->field($model, 'categories', \app\components\Constant::COLUMN(1))->widget(SelectizeDropDownList::class, [
        // load all categories
        'items' => \app\modules\blog\models\Kategori::getSelectizeList(),
        'options' => [
            'class' => 'form-control',
            // enable multiple
            'multiple' => true,
        ],
        'clientOptions' => [
            'plugins' => ['remove_button'],
            'valueField' => 'id',
            'labelField' => 'name',
            'searchField' => ['name'],
            'create' => false,
            'delimiter' => ',',
        ],
    ]) ?>
    <div class="clearfix"></div>
</div>