<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\annex\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\modules\blog\models\search\PostSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>
<div class="accordion" id="accordionExample">
	<div class="card shadow-none" style="background: transparent;">
		<div class="card-header" id="headingOne" style="background: transparent;">
			<h5 class="m-0">
				<?= Html::a('<i class="fa fa-plus"></i>' . Yii::t('cruds', 'Tambah Baru'), ['create'], ['class' => 'btn btn-success mb-1 mr-1', 'title' => Yii::t('cruds', 'Tambah Baru')]) ?>
				<button class="btn btn-default mb-1 mr-1" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
					Pencarian
				</button>
			</h5>
		</div>
		<div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
			<div class="card-body bg-white">

				<?php $form = ActiveForm::begin([
					'action' => ['index'],
					'layout' => 'horizontal',
					'method' => 'get',
				]); ?>
				<div class="d-flex  flex-wrap">
					<?= $form->field($model, 'title', \app\components\Constant::COLUMN(1))->textInput() ?>
					<?= $form->field($model, 'categories', \app\components\Constant::COLUMN(1))->dropDownList(
						ArrayHelper::map(\app\modules\blog\models\Kategori::find()->all(), 'id', 'nama_kategori'),
						['prompt' => Yii::t('cruds', '-- Pilih Kategori --')]
					) ?>
				</div>
				<div class="clearfix"></div>
				<div class="col-md-12">
					<div class="col-md-12">
						<div class="form-group">
							<?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
						</div>
					</div>
				</div>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>