<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\modules\blog\models\Post $model
 */

$this->title = Yii::t('cruds', 'Tambah Baru');
?>

<?php $form = \app\components\annex\ActiveForm::begin([
    'id' => 'Post',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
$model->setRender([
    'form' => $form
]);
?>
<div class="row">
    <div class="col-lg-8 col-md-12">
        <?php if (Yii::$app->request->isAjax == false) : ?>
            <div class="card m-b-30">
                <div class="card-body">
                <?php endif ?>
                <?= $this->render('_form_content', $model->render()); ?>
                <?php if (Yii::$app->request->isAjax == false) : ?>
                </div>
            </div>
        <?php endif ?>
    </div>
    <div class="col-lg-4 col-md-12">
        <?php if (Yii::$app->request->isAjax == false) : ?>
            <div class="card m-b-30">
                <div class="card-body">
                <?php endif ?>
                <?= $this->render('_form', $model->render()); ?>
                <?php if (Yii::$app->request->isAjax == false) : ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
<?php \app\components\annex\ActiveForm::end() ?>