<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use app\components\annex\ActiveForm;
use \app\components\annex\Tabs;

/**
 * @var yii\web\View $this
 * @var app\modules\android\models\AndroidBanner $model
 * @var app\components\annex\ActiveForm $form
 */

?>

<?php $form = ActiveForm::begin([
    'id' => 'AndroidBanner',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
?>
<?php echo $form->errorSummary($model); ?>

<div class="clearfix"></div>
<div class="d-flex  flex-wrap">

    <?= $form->field($model, 'gambar', \app\components\Constant::COLUMN(1))->widget(\kartik\file\FileInput::className(), [
        'options' => ['accept' => 'image/*'],
        'pluginOptions' => [
            'allowedFileExtensions' => ['jpg', 'png', 'jpeg', 'gif', 'bmp'],
        ],
    ]) ?>
    <?=         // modified by Defri Indra
    $form->field($model, 'id_kategori', \app\components\Constant::COLUMN())->widget(\kartik\select2\Select2::className(), [
        'name' => 'class_name',
        'model' => $model,
        'attribute' => 'id_kategori',
        'data' => \yii\helpers\ArrayHelper::map(app\modules\android\models\AndroidBannerKategori::find()->all(), 'id', 'nama_kategori'),
        'options' => [
            'placeholder' => $model->getAttributeLabel('id_kategori'),
            'multiple' => false,
            'disabled' => (isset($relAttributes) && isset($relAttributes['id_kategori'])),
        ]
    ]); ?>
    <?=         // modified by Defri Indra
    $form->field($model, 'id_route', \app\components\Constant::COLUMN())->widget(\kartik\select2\Select2::className(), [
        'name' => 'class_name',
        'model' => $model,
        'attribute' => 'id_route',
        'data' => \yii\helpers\ArrayHelper::map(app\modules\android\models\AndroidRoute::find()->all(), 'id', 'nama_route'),
        'options' => [
            'placeholder' => $model->getAttributeLabel('id_route'),
            'multiple' => false,
            'disabled' => (isset($relAttributes) && isset($relAttributes['id_route'])),
        ]
    ]); ?>
    <?= $form->field($model, 'judul', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'order', \app\components\Constant::COLUMN())->textInput(['type' => 'number']) ?>
    <?= $form->field($model, 'deskripsi', \app\components\Constant::COLUMN(1))->textarea(['rows' => 6]) ?>
    <div class="clearfix"></div>

    <div id="formparams">
        <?php
        if ($model->isNewRecord == false)
            echo $this->render('_form_params', ['params' => $params, 'model' => $model, 'form' => $form]);
        ?>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-offset-3 col-md-10">
        <?= Html::submitButton('<i class="fa fa-save"></i> ' . Yii::t('cruds', 'Simpan'), ['class' => 'btn btn-success']); ?>
        <?php if (Yii::$app->request->isAjax == false) : ?>
            <?= Html::a('<i class="fa fa-chevron-left"></i> ' . Yii::t('cruds', 'Kembali'), ['index'], ['class' => 'btn btn-default']) ?>
        <?php endif ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

<?php

$banner = $model->id ? "let banner = '{$model->id}';" : "let banner=null;";
$url = \yii\helpers\Url::to(['get-parameter']);
$js = <<<JS
$('#androidbanner-id_route').on('change', (event) => {
    $banner
    fetch("$url?id=" + event.target.value +"&banner="+banner).then(res => res.text()).then(res => {
        $("#formparams").html(res);
    });
});
JS;

$this->registerJs($js);
