<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\annex\Tabs;
use app\components\ModalButton;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\modules\android\models\search\AndroidBannerSearch $searchModel
 */

$this->title = Yii::t('cruds', 'Android Banner');
$this->params['breadcrumbs'][] = $this->title;
$module = $this->context->module->id;
?>

<p>
    <?= ModalButton::a('<i class="fa fa-plus"></i>' . Yii::t('cruds', 'Tambah Banner'), ['/' . $module . '/android-banner/create'], ['class' => 'btn btn-success mb-1 mr-1', 'title' => Yii::t('cruds', 'Tambah Banner')]) ?>
    <?= ModalButton::a('<i class="fa fa-plus"></i>' . Yii::t('cruds', 'Tambah Kategori'), ['/' . $module . '/android-banner-kategori/create'], ['class' => 'btn btn-success mb-1 mr-1', 'title' => Yii::t('cruds', 'Tambah Kategori')]) ?>
    <?= ModalButton::a('<i class="fa fa-plus"></i>' . Yii::t('cruds', 'Tambah Rute'), ['/' . $module . '/android-route/create'], ['class' => 'btn btn-success mb-1 mr-1', 'title' => Yii::t('cruds', 'Tambah Rute')]) ?>
</p>


<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-body">
                <?php $this->beginBlock('banner'); ?>
                <?= $this->render('_index', ['dataProvider' => $bannerDataProvider]); ?>
                <?php $this->endBlock(); ?>
                <?php $this->beginBlock('kategori'); ?>
                <?= $this->render('../android-banner-kategori/_index', ['dataProvider' => $kategoriBannerDataProvider]); ?>
                <?php $this->endBlock(); ?>
                <?php $this->beginBlock('route'); ?>
                <?= $this->render('../android-route/_index', ['dataProvider' => $routeDataProvider]); ?>
                <?php $this->endBlock(); ?>
                <!-- tabs -->
                <?= Tabs::widget([
                    'items' => [
                        [
                            'label' => Yii::t('cruds', 'Semua Banner'),
                            'content' => $this->blocks['banner'],
                            'active' => true,
                        ],
                        [
                            'label' => Yii::t('cruds', 'Kategori'),
                            'content' => $this->blocks['kategori'],
                            'active' => false,
                        ],
                        [
                            'label' => Yii::t('cruds', 'Rute'),
                            'content' => $this->blocks['route'],
                            'active' => false,

                        ],
                    ],
                ]) ?>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\Pjax::end() ?>