<?php
/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
* @var yii\web\View $this
* @var app\models\search\UserSearch $model
* @var yii\widgets\ActiveForm $form
*/
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
    ]); ?>

    		<?= $form->field($model, 'id') ?>

		<?= $form->field($model, 'gid') ?>

		<?= $form->field($model, 'username') ?>

		<?= $form->field($model, 'password') ?>

		<?= $form->field($model, 'name') ?>

		<?php // echo $form->field($model, 'phone') ?>

		<?php // echo $form->field($model, 'email') ?>

		<?php // echo $form->field($model, 'secret_token') ?>

		<?php // echo $form->field($model, 'fcm_token') ?>

		<?php // echo $form->field($model, 'role_id') ?>

		<?php // echo $form->field($model, 'photo_url') ?>

		<?php // echo $form->field($model, 'is_active') ?>

		<?php // echo $form->field($model, 'last_login') ?>

		<?php // echo $form->field($model, 'last_logout') ?>

		<?php // echo $form->field($model, 'token') ?>

		<?php // echo $form->field($model, 'token_created_at') ?>

		<?php // echo $form->field($model, 'token_is_used') ?>

		<?php // echo $form->field($model, 'status') ?>

		<?php // echo $form->field($model, 'flag') ?>

		<?php // echo $form->field($model, 'registered_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
