<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "t_master_satuan".
 *
 * @property string $nama
 * @property string $keterangan
 * @property integer $jenis_satuan_id
 * @property integer $flag
 * @property integer $id
 *
 * @property \app\models\MasterMaterial[] $masterMaterials
 * @property string $aliasModel
 */
abstract class MasterSatuan extends \yii\db\ActiveRecord
{
    /**
     * BaseModel rules. 
     **/
    use \app\traits\ModelTrait;

    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';
    public $_render = [];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 't_master_satuan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => \app\components\behaviors\UUIDBehavior::class,
                'model' => get_called_class(),
                'primaryKey' => 'id',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'keterangan', 'jenis_satuan_id'], 'required'],
            [['jenis_satuan_id', 'flag'], 'integer'],
            [['nama'], 'string', 'max' => 20],
            [['keterangan'], 'string', 'max' => 100],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'nama' => Yii::t('models', 'Nama'),
            'keterangan' => Yii::t('models', 'Keterangan'),
            'jenis_satuan_id' => Yii::t('models', 'Jenis Satuan'),
            'flag' => Yii::t('models', 'Flag'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMasterMaterials()
    {
        return $this->hasMany(\app\models\MasterMaterial::class, ['id_satuan' => 'id']);
    }





    public function scenarios()
    {
        $parent = parent::scenarios();

        $columns = [
            'id',
            'nama',
            'keterangan',
            'jenis_satuan_id',
            'flag',
        ];

        $parent[static::SCENARIO_CREATE] = $columns;
        $parent[static::SCENARIO_UPDATE] = $columns;
        return $parent;
    }

    /**
     * @inheiritance
     */
    public function fields()
    {
        $parent = parent::fields();

        if(isset($parent['id'])) :
            unset($parent['id']);
            $parent['id'] = function($model) {
                return $model->id;
            };
        endif;
        if(isset($parent['nama'])) :
            unset($parent['nama']);
            $parent['nama'] = function($model) {
                return $model->nama;
            };
        endif;
        if(isset($parent['keterangan'])) :
            unset($parent['keterangan']);
            $parent['keterangan'] = function($model) {
                return $model->keterangan;
            };
        endif;
        if(isset($parent['jenis_satuan_id'])) :
            unset($parent['jenis_satuan_id']);
            $parent['jenis_satuan_id'] = function($model) {
                return $model->jenis_satuan_id;
            };
        endif;
        if(isset($parent['flag'])) :
            unset($parent['flag']);
            $parent['flag'] = function($model) {
                return $model->flag;
            };
        endif;


    // $parent['master_material'] = function($model) {
    //     $rel = $model->masterMaterials;
    //     if($rel) :
    //         return $rel;
    //     endif;
    //     return null;
    // };

        return $parent;
    }


    public static function faker($count = 10){
        $faker= \Faker\Factory::create();
        $faker->addProvider(new \app\components\faker\provider\MyImage($faker));
        $data = [];
        $maxId = static::find()->max('id');

        // relational data
        for ($i = 0; $i < $count; $i++) {
            $data[] = [ 
                "nama" => $faker->name,
                "keterangan" => $faker->paragraphs($nb = 3, $asText = true),
                "jenis_satuan_id" => $faker->unique()->numberBetween($maxId, $maxId + $count),
                "flag" => $faker->numberBetween(0, 1),
                "id" => $faker->unique()->numberBetween($maxId, $maxId + $count),
            ];
        }
        return $data;
    }

}
