<?php
/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
* @var yii\web\View $this
* @var app\models\search\Smarthome $model
* @var yii\widgets\ActiveForm $form
*/
?>

<div class="smarthome-search">

    <?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
    ]); ?>

    		<?= $form->field($model, 'id') ?>

		<?= $form->field($model, 'id_user') ?>

		<?= $form->field($model, 'nama') ?>

		<?= $form->field($model, 'suhu') ?>

		<?= $form->field($model, 'kelembapan') ?>

		<?php // echo $form->field($model, 'tegangan') ?>

		<?php // echo $form->field($model, 'daya') ?>

		<?php // echo $form->field($model, 'ampere') ?>

		<?php // echo $form->field($model, 'daya_sebelumnya') ?>

		<?php // echo $form->field($model, 'ampere_sebelumnya') ?>

		<?php // echo $form->field($model, 'token') ?>

		<?php // echo $form->field($model, 'flag') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('cruds', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('cruds', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
