<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use \dmstr\helpers\Html;
use app\components\annex\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\search\ProyekSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>
<div class="accordion" id="accordionExample">
    <div class="card shadow-none" style="background: transparent;">
        <div class="card-header" id="headingOne" style="background: transparent;">
            <h5 class="m-0">
                <button class="btn btn-default" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Pencarian
                </button>
            </h5>
        </div>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body bg-white">

                <div class="notification-search">

                    <?php $form = ActiveForm::begin([
                        'action' => ['index'],
                        'method' => 'get',
                    ]); ?>

                    <?php // $form->field($model, 'id') ?>

                    <?= $form->field($model, 'user_id') ?>

                    <?= $form->field($model, 'title') ?>

                    <?= $form->field($model, 'description') ?>

                    <?= $form->field($model, 'controller') ?>

                    <?php // echo $form->field($model, 'android_route') 
                    ?>

                    <?php // echo $form->field($model, 'params') 
                    ?>

                    <?php // echo $form->field($model, 'read') 
                    ?>

                    <?php // echo $form->field($model, 'created_at') 
                    ?>

                    <div class="form-group">
                        <?= Html::submitButton(Yii::t('cruds', 'Search'), ['class' => 'btn btn-primary']) ?>
                        <?= Html::resetButton(Yii::t('cruds', 'Reset'), ['class' => 'btn btn-default']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>

                </div>
            </div>
        </div>
    </div>
</div>