<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\ModalButton;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\modules\notification\models\search\NotificationSearch $searchModel
 */

$this->title = Yii::t('cruds', 'Notification');
$this->params['breadcrumbs'][] = $this->title;
?>

<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="row">
    <div class="col-md-12 mb-2">
        <?= $this->render('_search', ['model' => $searchModel]) ?>
    </div>
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-body">
                <div class="table-responsive">
                    <?= GridView::widget([
                        'layout' => '{summary}{items}{pager}',
                        'dataProvider' => $dataProvider,
                        'pager'        => [
                            'class'          => app\components\annex\LinkPager::class,
                            'firstPageLabel' => Yii::t('cruds', 'First'),
                            'lastPageLabel'  => Yii::t('cruds', 'Last')
                        ],
                        'filterModel' => false,
                        'tableOptions' => ['class' => 'table table-striped table-borderless table-hover'],
                        'headerRowOptions' => ['class' => 'x'],
                        'columns' => [
                            [
                                'class' => yii\grid\DataColumn::class,
                                'attribute' => 'user_id',
                                'value' => function ($model) {
                                    if ($rel = $model->user) {
                                        return $rel->name;
                                    } else {
                                        return '';
                                    }
                                },
                                'format' => 'raw',
                            ],
                            [
                                'attribute' => 'title',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'description',
                                'format' => 'ntext',
                            ],
                            [
                                'attribute' => 'controller',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'params',
                                'format' => 'ntext',
                            ],
                            [
                                'attribute' => 'android_route',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'read',
                                'format' => 'text',
                                'value' => function ($model) {
                                    return $model->read ? '<span class="label label-success">' . Yii::t('cruds', 'Yes') . '</span>' : '<span class="label label-danger">' . Yii::t('cruds', 'No') . '</span>';
                                },
                            ],
                            [
                                'attribute' => 'created_at',
                                'format' => 'iddate',
                            ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\Pjax::end() ?>