<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\ModalButton;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\modules\accesslog\models\search\AccessLogSearch $searchModel
 */

$this->title = Yii::t('cruds', 'Access Log');
$this->params['breadcrumbs'][] = $this->title;
?>
<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-body">
                <div class="table-responsive">
                    <?= GridView::widget([
                        'layout' => '{summary}{items}{pager}',
                        'dataProvider' => $dataProvider,
                        'pager'        => [
                            'class'          => app\components\annex\LinkPager::class,
                            'firstPageLabel' => Yii::t('cruds', 'First'),
                            'lastPageLabel'  => Yii::t('cruds', 'Last')
                        ],
                        'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table table-striped table-borderless table-hover'],
                        'headerRowOptions' => ['class' => 'x'],
                        'columns' => [

                            \app\components\ActionAjaxButton::getButtons(['template' => '{view}']),

                            [
                                'attribute' => 'type',
                                'format' => 'text',
                                'filter' => \app\modules\accesslog\models\AccessLog::getTypes(),
                                'value' => function ($model) {
                                    return $model->getType();
                                },
                            ],
                            [
                                'attribute' => 'path',
                                'format' => 'text',
                            ],
                            // [
                            //     'attribute' => 'request',
                            //     'format' => 'ntext',
                            // ],
                            // [
                            //     'attribute' => 'response',
                            //     'format' => 'ntext',
                            // ],
                            [
                                'attribute' => 'method',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'ip',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'username',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'created_at',
                                'format' => 'iddate',
                            ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\Pjax::end() ?>